# Generated by Django 4.2.7 on 2025-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='activationcode',
            name='student',
        ),
        migrations.AddField(
            model_name='activationcode',
            name='prefix',
            field=models.CharField(default='ABC', max_length=3),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
